version: '3.8'

services:
  pulse-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pulse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./be
    environment:
      DATABASE_URL: postgresql://postgres:password@pulse-db:5432/pulse_db?schema=public
      PORT: 3001
      FRONTEND_URL: http://localhost:8100
      BETTER_AUTH_URL: http://localhost:3001
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - pulse-db

  frontend:
    build:
      context: ./fe
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "8100:8100"
    depends_on:
      - backend

volumes:
  postgres_data:
